### ISSUE TITLE
Can't it be used with Blazor Webassembly?

### ISSUE THREAD

**Issue by s1v** [Cinchoo/ChoETL#162]
When I try to use it with Blazor Webassembly, I get the following error...

```
1) Exception Information
*********************************************
Exception Type: System.ArgumentNullException
Message: Value cannot be null. (Parameter 'IniFilePath')
ParamName: IniFilePath
TargetSite: Void ArgumentNotNullOrEmpty(System.String, System.String)
Data: System.Collections.ListDictionaryInternal
HelpLink: NULL
Source: ChoETL.Core
HResult: -2147467261

StackTrace Information
*********************************************
   at ChoETL.ChoGuard.ArgumentNotNullOrEmpty(String argumentValue, String argumentName)
   at ChoETL.ChoIniFile.New(String iniFilePath, String sectionName)
   at ChoETL.ChoETLFramework._Initialize()
```

Can't it be used with Blazor Webassembly?

**Comment by Cinchoo** [comment]
pls set `ChoETLFrxBootstrap.IsSandboxEnvironment = true` at the application startup. Let me know.

**Comment by s1v** [comment]
It's working.
Thx awesome package, and support.

**Comment by KoalaBear84** [comment]
I've had to do the same for (at least) .NET 7 when published.
