### ISSUE TITLE
I am currently getting error when reading a parquet file 

### ISSUE THREAD

**Issue by RushkaVenter** [Cinchoo/ChoETL#164]
I am currently trying to run a simple example of reading a parquet file:

foreach (dynamic e in new ChoParquetReader("test.parquet"))
                Console.WriteLine("Id: " + e.id);

However, it is returning the below error, even while trying different read examples.

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.Func`2<System.Object,System.Type> ChoETL.ChoFileRecordConfiguration.get_RecordSelector()'.
  Source=ChoETL.Parquet
  StackTrace:
   at ChoETL.ChoParquetRecordReader.<AsEnumerable>d__17.MoveNext()
   at ChoETL.ChoParquetRecordReader.<AsEnumerable>d__13.MoveNext()
   at ChoETL.ChoParquetReader`1.<>c__DisplayClass35_0.<GetEnumerator>b__0()
   at ChoETL.ChoEnumeratorWrapper.ChoEnumeratorWrapperInternal`1.MoveNext()
   at ChoETL.ChoEnumeratorWrapper.<BuildEnumerable>d__0`1.MoveNext()
   at ParquetChoETLSpike.Program.<Main>d__0.MoveNext() in G:\Anglo\Research\ParquetChoETLSpike\Program.cs:line 29

**Comment by Cinchoo** [comment]
Pls state the library versions? ChoETL.Parquet and ChoETL (both).
.net framework version? .NET framework / .NET Core etc.
ChoETL package install commands u have used?

**Comment by Cinchoo** [comment]
It must be 

ChoETL - 1.2.1.21
ChoETL.Parquet - 1.0.1.12

**Comment by RushkaVenter** [comment]
I was using:

ChoETL - 1.2.1.28 (I just installed the latest stable version)
ChoETL.Parquet - 1.0.1.12

Switching to ChoETL - 1.2.1.21 resolved the issue.

**Comment by Cinchoo** [comment]
Latest release synced up all plug-ins. Take the latest and give it try.
