### ISSUE TITLE
Error writing Parquet from JSON "Message=Method not found: 'System.String ChoETL.IChoArrayItemFieldNameOverrideable.GetFieldName(System.String, System.String, Char, Int32)'"

### ISSUE THREAD

**Issue by richwallace** [Cinchoo/ChoETL#174]
I have an Azure Function that listens for events from Azure Event Grid that I'd like to convert the data json payload to parquet.  Not sure if I'm missing something in my code here, or if there is a legit issue.

I am using the following packages:

ChoETL - 1.2.1.42
ChoETL.Parquet - 1.0.1.20

When the event comes in, I load the "Data" element to POCO, and run the following:

```
// Handle the event
var objects = new List<Contact>();
objects.Add(eventGridEvent.Data.ToObjectFromJson<Contact>());
using (var writer = new ChoParquetWriter("output.parquet"))
{
     writer.Write(objects); // <-- Error occurs
}
```

I've also tried a single object with the same error:

```
// Handle the custom event
var contact = eventGridEvent.Data.ToObjectFromJson<Contact>();
using (var writer = new ChoParquetWriter("output.parquet"))
{
     writer.Write(contact); // <-- Error occurs
}
```

Full error detail:

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.String ChoETL.IChoArrayItemFieldNameOverrideable.GetFieldName(System.String, System.String, Char, Int32)'.
  Source=ChoETL.Parquet
  StackTrace:
   at ChoETL.ChoParquetRecordConfiguration.NewFieldConfiguration(Int32& position, String declaringMember, PropertyDescriptor pd, Nullable`1 arrayIndex, String displayName, String dictKey, Boolean ignoreAttrs, Action`1 mapper)
   at ChoETL.ChoParquetRecordConfiguration.DiscoverRecordFields(Type recordType, Int32& position, String declaringMember, Boolean optIn, PropertyDescriptor propDesc, List`1 recordFieldConfigurations)
   at ChoETL.ChoParquetRecordConfiguration.DiscoverRecordFields(Type recordType, Int32& pos, Boolean clear, List`1 recordFieldConfigurations)
   at ChoETL.ChoParquetRecordConfiguration.MapRecordFields(Type[] recordTypes)
   at ChoETL.ChoParquetRecordWriter.GetFields(Object record)
   at ChoETL.ChoParquetRecordWriter.<WriteTo>d__37.MoveNext()
   at ChoETL.ChoUtility.Loop(IEnumerable e, Action preActionCallback, Action`1 postActionCallback)
   at ChoETL.ChoParquetWriter`1.Write(IEnumerable`1 records)
   at EventToADLSParquet.EventSubscriber.Run(EventGridEvent eventGridEvent, ILogger log) in E:\_github\csharp-azure-function-json-parquet\EventToADLSParquet\EventSubscriber.cs:line 29
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidMethodInvoker.cs:line 21
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.<InvokeAsync>d__10.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
```

Here is the POCO:

```
using System;
using System.ComponentModel.DataAnnotations;

namespace EventToADLSParquet.Models
{
    public class Contact
    {
        /// <summary>
        /// Gets or sets the contact identifier
        /// </summary>
        public int id { get; set; }

        /// <summary>
        /// Gets or sets the contacts's first name
        /// </summary>
        /// <value>The contacts's first name.</value>
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Must be between 2 and 50 characters")]
        public string firstName { get; set; }

        /// <summary>
        /// Gets or sets the contacts's last name
        /// </summary>
        /// <value>The contacts's last name.</value>
        [Required]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Must be between 2 and 50 characters")]
        public string lastName { get; set; }

        /// <summary>
        /// Gets or sets the contacts's display name
        /// </summary>
        /// <value>The contacts's display name.</value>
        [Required]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Must be between 2 and 50 characters")]
        public string displayName { get; set; }

        /// <summary>
        /// Contact created by name/service
        /// </summary>
        public string createdBy { get; set; }

        /// <summary>
        /// Date contact created
        /// </summary>
        public DateTime createdUtcDate { get; set; }

        /// <summary>
        /// Contact last modified by name/service
        /// </summary>
        public string lastModifiedBy { get; set; }

        /// <summary>
        /// Date contact last modified
        /// </summary>
        public DateTime lastModifiedUtcDate { get; set; }
    }
}
```

Here is the json that is extracted from the event payload that I am attempting to convert to parquet:

```
 {
	"id": 6720,
	"firstName": "Thor",
	"lastName": "Odinson",
        "displayName": "Thor Odinson",
	"createdBy": "apisvcdev",
	"createdUtcDate": "2022-01-25T22:46:31.765Z",
	"lastModifiedBy": "apisvcdev",
	"lastModifiedUtcDate": "2022-01-25T22:46:31.765Z"
}
```

**Comment by Cinchoo** [comment]
Use ChoETL v1.2.1.41

FYI, will be pushing new release of ChoETL.Parquet in a week.

**Comment by richwallace** [comment]
Had to drop down to 1.2.1.40.  Error remains in 1.2.1.41 - just FYI.

Thank you!
