### ISSUE TITLE
Can we read CSV file with Shift-JIS encoding? 

### ISSUE THREAD

**Issue by sithu-ab** [Cinchoo/ChoETL#178]
I'm reading CSV file with Shift-JIS encoding. It contains Japanese header.

    var p = new ChoCSVReader(input_file).WithFirstLineHeader();
    var tbl = p.AsDataTable();

I'm getting the error of duplicate field names. I believe it is because of Japanese header is not correctly read. Looks like the error comes from `AsDataTable()`.

```
1) Exception Information
*********************************************
Exception Type: ChoETL.ChoRecordConfigurationException
TargetSite: Void Validate(System.Object)
Message: Duplicate field name(s) [Name: ?????N??] found.
Data: System.Collections.ListDictionaryInternal
HelpLink: NULL
Source: ChoETL.Core
HResult: -2146232832

StackTrace Information
*********************************************
   at ChoETL.ChoCSVRecordConfiguration.Validate(Object state)
   at ChoETL.ChoCSVRecordReader.<>c__DisplayClass24_0.<AsEnumerable>b__0(Tuple`2 pairElement)
   at ChoETL.ChoPeekEnumerator`1.MoveToNext()
   at ChoETL.ChoCSVRecordReader.AsEnumerable(Object source, TraceSwitch traceSwitch, Func`2 filterFunc)+MoveNext()
   at ChoETL.ChoEnumerableDataReader..ctor(IEnumerable collection, IChoDeferedObjectMemberDiscoverer dom)
   at ChoETL.ChoCSVReader`1.AsDataReader(Action`1 membersDiscovered)
   at ChoETL.ChoCSVReader`1.AsDataReader()
   at ChoETL.ChoCSVReader`1.AsDataTable(String tableName)
```

**Comment by Cinchoo** [comment]
try this

```
var p = new ChoCSVReader(input_file).WithFirstLineHeader().Configure(c => c.Encoding = Encoding.GetEncoding("*** ENCODING NAME ****"));
var tbl = p.AsDataTable();
```

**Comment by sithu-ab** [comment]
Thank you. This resolved the issue.
    
    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
    var p = new ChoCSVReader(input_file).WithFirstLineHeader().Configure(c => c.Encoding = Encoding.GetEncoding("Shift-JIS"));
    var tbl = p.AsDataTable();

Without the first line, I got this error.

`Message: 'Shift-JIS' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')`
