### ISSUE TITLE
Parquet: Specified method is not supported

### ISSUE THREAD

**Issue by tunlige** [Cinchoo/ChoETL#233]
I'm struggling with this exception:

```
Specified method is not supported.
Source: Parquet
Meth: System.Array GetArray(Int32, Boolean, Boolean)
at Parquet.Data.NonDataDataTypeHandler.GetArray(Int32 minCount, Boolean rent, Boolean isNullable) in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/Data/NonDataDataTypeHandler.cs:line 27
at Parquet.File.DataColumnReader.TryReadDictionaryPage(PageHeader ph, Array& dictionary, Int32& dictionaryOffset) in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/File/DataColumnReader.cs:line 151
at Parquet.File.DataColumnReader.Read() in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/File/DataColumnReader.cs:line 79
at Parquet.ParquetRowGroupReader.ReadColumn(DataField field) in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/ParquetRowGroupReader.cs:line 64
at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at ChoETL.ChoParquetRecordReader.d__22.MoveNext()
at ChoETL.ChoParquetRecordReader.d__25.MoveNext()
at ChoETL.ChoParquetRecordReader.d__20.MoveNext()
at ChoETL.ChoParquetReader`1.<>c__DisplayClass40_0.b__0()
at ChoETL.ChoEnumeratorWrapper.ChoEnumeratorWrapperInternal`1.MoveNext()
at ChoETL.ChoEnumeratorWrapper.d__0`1.MoveNext()
at System.Linq.Enumerable.d__25`1.MoveNext()
at Test.Download(DateTime date) in C:\Development\test\test.cs:line 125
System.NotSupportedException: Specified method is not supported.
at Parquet.Data.NonDataDataTypeHandler.GetArray(Int32 minCount, Boolean rent, Boolean isNullable) in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/Data/NonDataDataTypeHandler.cs:line 27
at Parquet.File.DataColumnReader.TryReadDictionaryPage(PageHeader ph, Array& dictionary, Int32& dictionaryOffset) in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/File/DataColumnReader.cs:line 151
at Parquet.File.DataColumnReader.Read() in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/File/DataColumnReader.cs:line 79
at Parquet.ParquetRowGroupReader.ReadColumn(DataField field) in /home/runner/work/parquet-dotnet/parquet-dotnet/src/Parquet/ParquetRowGroupReader.cs:line 64
at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at ChoETL.ChoParquetRecordReader.d__22.MoveNext()
at ChoETL.ChoParquetRecordReader.d__25.MoveNext()
at ChoETL.ChoParquetRecordReader.d__20.MoveNext()
at ChoETL.ChoParquetReader`1.<>c__DisplayClass40_0.b__0()
at ChoETL.ChoEnumeratorWrapper.ChoEnumeratorWrapperInternal`1.MoveNext()
at ChoETL.ChoEnumeratorWrapper.d__0`1.MoveNext()
at System.Linq.Enumerable.d__25`1.MoveNext()

```
The parquet file contains many columns, but I have stripped my column to select only one column

```
public class IHSVessels
    {
        public string ClassNarrative { get; set; }
        // removed other properties
        public long IHSLRorIMOShipNo { get; set; }
}

```

```

void Download(DateTime date)
{
var filename="test.parquet";
downloadFile(filename);
ChoParquetRecordConfiguration config = new ChoParquetRecordConfiguration();
                config.ThrowAndStopOnMissingField = false;
                config.ThrowExceptionIfDynamicPropNotExists = false;
                config.IgnoreField("DataSetVersion");

                using (ChoParquetReader<IHSVessels> r = new ChoParquetReader<IHSVessels>(filename, config)
                    .ParquetOptions(o => o.TreatByteArrayAsString = true )
                    .ErrorMode(ChoErrorMode.IgnoreAndContinue))
                {
                    foreach (var item in r.Take(10))
                    {
                        Console.Writeline(item.IHSLRorIMOShipNo+", ");

                    }
                }
```
I have tested the file with [ParquetViewer](https://github.com/mukunku/ParquetViewer) and it works if I remove the column "DataSetVersion". So I tried to do the same here but it does not work.
So I can't figure out what is causing this exception.
Can anyone help me out here.

**Comment by Cinchoo** [comment]
pls post sample parquet data file.

**Comment by tunlige** [comment]
Hi. 
Can I send it to you on the email on you homepage?

**Comment by Cinchoo** [comment]
yes, that works.

**Comment by tunlige** [comment]
Done

**Comment by Cinchoo** [comment]
got the problem, one of the field `DataSetVersion` is not data field, it is struct. hence the issue. 

Applied fix in the library to ignore them. released v1.0.1.23-beta4

Give it a try and let me know.

**Comment by tunlige** [comment]
Struggling a little with this error now:


Method not found: 'Void ChoETL.ChoETLRecordHelper.ConvertNSetMemberValue(System.Object, System.String, ChoETL.ChoRecordFieldConfiguration, System.Object ByRef, System.Globalization.CultureInfo, ChoETL.ChoRecordConfiguration)'.
Source: ChoETL.Parquet
Meth: Boolean FillRecord(System.Object ByRef, System.Tuple`2[System.Int64,System.Collections.Generic.IDictionary`2[System.String,System.Object]])
at ChoETL.ChoParquetRecordReader.FillRecord(Object& rec, Tuple`2 pair)
at ChoETL.ChoParquetRecordReader.LoadNode(Tuple`2 pair, Object& rec)
at ChoETL.ChoParquetRecordReader.d__25.MoveNext()
at ChoETL.ChoParquetRecordReader.d__20.MoveNext()
at ChoETL.ChoParquetReader`1.<>c__DisplayClass40_0.b__0()
at ChoETL.ChoEnumeratorWrapper.ChoEnumeratorWrapperInternal`1.MoveNext()
at ChoETL.ChoEnumeratorWrapper.d__0`1.MoveNext()
at ChoETL.ChoParquetReader`1.Read()
at PLM.Core.Models.AWS.IHSVessels.Download(DateTime date) in C:\Development\PLM\PLM.Core\Models\AWS\IHSVessels.cs:line 124
System.MissingMethodException: Method not found: 'Void ChoETL.ChoETLRecordHelper.ConvertNSetMemberValue(System.Object, System.String, ChoETL.ChoRecordFieldConfiguration, System.Object ByRef, System.Globalization.CultureInfo, ChoETL.ChoRecordConfiguration)'.
at ChoETL.ChoParquetRecordReader.FillRecord(Object& rec, Tuple`2 pair)
at ChoETL.ChoParquetRecordReader.LoadNode(Tuple`2 pair, Object& rec)
at ChoETL.ChoParquetRecordReader.d__25.MoveNext()
at ChoETL.ChoParquetRecordReader.d__20.MoveNext()
at ChoETL.ChoParquetReader`1.<>c__DisplayClass40_0.b__0()
at ChoETL.ChoEnumeratorWrapper.ChoEnumeratorWrapperInternal`1.MoveNext()
at ChoETL.ChoEnumeratorWrapper.d__0`1.MoveNext()
at ChoETL.ChoParquetReader`1.Read()

**Comment by tunlige** [comment]
Thank you so much for helping me so quickly. 
Really appreciate it. 
Everything works as expected now.
