### ISSUE TITLE
TSV - Exception on blank field value

### ISSUE THREAD

**Issue by jamesflagg** [Cinchoo/ChoETL#289]
Unit test to reproduce the problem:
`
using ChoETL;

namespace UnitTests
{
    public class ChoTests
    {
        [Fact]
        public void CanReadTabDelimitedWithBlankFieldValue()
        {
            using (var reader = ChoTSVReader.LoadText("A\t\tB").ErrorMode(ChoErrorMode.ThrowAndStop))
            {
                foreach(var record in reader)
                {
                    Assert.NotNull(record);
                    Assert.Equal("A", record.Column1);
                    Assert.Null(record.Column2);
                    Assert.Equal("B", record.Column3);
                }
            }
        }
    }
}
`
This throws an exception, when it should gracefully populate the record.
It is apparently a side effect of the delimiter (tab) being considered whitespace.
Stack trace:
`
   at ChoETL.ChoUtility.RightOf(String source, String searchText)
  at ChoETL.ChoCSVRecordReader.GetFieldValues(String line)
  at ChoETL.ChoCSVRecordReader.FillRecord(Object rec, Tuple`2 pair)
  at ChoETL.ChoCSVRecordReader.LoadLine(Tuple`2 pair, Object& rec)
  at ChoETL.ChoCSVRecordReader.AsEnumerable(Object source, TraceSwitch traceSwitch, Func`2 filterFunc)+MoveNext()
 at ChoETL.ChoEnumeratorWrapper.BuildEnumerable[T](Func`1 moveNext, Func`1 current, Action dispose)+MoveNext()

 `

**Comment by Cinchoo** [comment]
Applied fix, released v1.2.1.60

Sample fiddle: https://dotnetfiddle.net/9kp7Aw
