### ISSUE TITLE
Can't find Component property in System.String object.

### ISSUE THREAD

**Issue by chuongmep** [Cinchoo/ChoETL#310]
The problem cause when I'm try export datatable push to parquet format.
```xml
System.ApplicationException : Can't find Component property in System.String object.
   at ChoETL.ChoType.GetPropertyValue(Object target, String name)
   at ChoETL.ChoObjectEx.GetNestedMember(Object target, String propName, Object& parent, String& memberName, Boolean createSubKeysIfNotExists, Func`1 factory)
   at ChoETL.ChoObjectEx.GetNestedMember(Object target, String propName, Object& parent, String& memberName, Boolean createSubKeysIfNotExists, Func`1 factory)
   at ChoETL.ChoObjectEx.SetNestedPropertyValue(Object target, String propName, Object propValue, Boolean createSubKeysIfNotExists, Func`1 factory)
   at ChoETL.ChoDynamicObject.SetNestedPropertyValue(String propName, Object propValue)
   at ChoETL.ChoDynamicObject._SetPropertyValue(String name, Object value)
   at ChoETL.ChoDynamicObject.SetPropertyValue(String name, Object value)
   at CallSite.Target(Closure , CallSite , Object , String , Object )
   at ChoETL.ChoParquetRecordWriter.ToText(Int64 index, Object rec, Object& recText)
   at ChoETL.ChoParquetRecordWriter.WriteTo(Object writer, IEnumerable`1 records, Func`2 predicate)+MoveNext()
   at ChoETL.ChoUtility.Loop(IEnumerable e, Action preActionCallback, Action`1 postActionCallback)
   at ChoETL.ChoParquetWriter`1.Write(T record)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at ChoETL.ChoParquetWriter`1.Write(DataTable dt)
```

**Comment by chuongmep** [comment]
File data have issue demo : 
[result.csv](https://github.com/Cinchoo/ChoETL/files/14328787/result.csv)

**Comment by Cinchoo** [comment]
Set `ChoETLSettings.KeySeparator = '!';` at the main() method.

Because input csv file comes with . character in the file header.

**Comment by chuongmep** [comment]
@Cinchoo  do we have any way to keep origin of column title ?
