### ISSUE TITLE
Expecting custom csv output when using complex json to csv

### ISSUE THREAD

**Issue by Kunjahamed-P** [Cinchoo/ChoETL#67]
Hi,
i Expecting custom csv output for the input json . the json is complex ,nested and large size.
the sample json is
```
{
    "data": {
        "getUsers": [
            {
                "UserProfileDetail": {
                    "UserStatus": {
                        "name": "User One"
                    },
                    "UserStatusDate": "2018-10-31T06:12:42+00:00",
                    "EnrollId": "am**********************************",
                    "lastDate": "2019-07-22T03:05:39.0245313-04:00"
                },
                "UserInformation": {
                    "Id": 1111122,
                    "firstName": "*****",
                    "middleName": null,
                    "lastName": "*****",
                    "otherNames": null,
                    "UserType": {
                        "name": "CP"
                    },
                    "primaryState": "MA",
                    "otherState": [
                        "MA",
                        "BA"
                    ],
                    "UserLicense": [
                        {
                            "licenseState": "MA",
                            "licenseNumber": "000000000",
                            "licenseStatus": null
                        }
                    ],
                    "Setting": "ADMINISTRATIVE",
                    "primaryEmail": "*****@*****.com",
                    "modifiedAt": null,
                    "createdAt": null
                }
            },
            {
                "UserProfileDetail": {
                    "UserStatus": {
                        "name": "User Two"
                    },
                    "UserStatusDate": "2019-10-31T06:12:42+00:00",
                    "EnrollId": "am**********************************",
                    "lastDate": "2019-07-22T03:05:39.0245313-04:00"
                },
                "UserInformation": {
                    "Id": 443333,
                    "firstName": "*****",
                    "middleName": "Jhon",
                    "lastName": "*****",
                    "otherNames": null,
                    "UserType": {
                        "name": "AP"
                    },
                    "primaryState": "AK",
                    "otherState": [
                        "MP",
                        "CLT"
                    ],
                    "UserLicense": [
                        {
                            "licenseState": "KL",
                            "licenseNumber": "000000220",
                            "licenseStatus": "Valid"
                        }
                    ],
                    "Setting": "ADMINISTRATIVE",
                    "primaryEmail": "*****@*****.com",
                    "modifiedAt": null,
                    "createdAt": null
                }
            }
        ]
    },
    "errors": [
        {
            "message": "GraphQL.ExecutionError: 13614711 - NO__DATA",
            "extensions": {
                "code": "212"
            }
        },
        {
            "message": "GraphQL.ExecutionError: 13614712 - NO__DATA",
            "extensions": {
                "code": "212"
            }
        },
        {
            "message": "GraphQL.ExecutionError: Cannot return null for non-null type. Field: PrivilegeFlag, Type: Boolean!.\r\n   at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node)\r\n   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)",
            "locations": [
                {
                    "line": 374,
                    "column": 9
                }
            ],
            "path": [
                "getUsers",
                "3",
                "UserAffiliation",
                "0",
                "Affiliation",
                "admittingPrivilegeFlag"
            ],
            "extensions": {
                "code": "ID: 1454790"
            }
        },
        {
            "message": "GraphQL.ExecutionError: Cannot return null for non-null type. Field: admittingArrangementFlag, Type: Boolean!.\r\n   at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node)\r\n   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)",
            "locations": [
                {
                    "line": 403,
                    "column": 9
                }
            ],
            "path": [
                "getUsers",
                "3",
                "UserAffiliation",
                "0",
                "Affiliation",
                "admittingArrangementFlag"
            ],
            "extensions": {
                "code": "ID: 13614790"
            }
        }
    ]
}
```

the expected output sample is

```
UserProfileDetail_UserStatus_name,UserProfileDetail_UserStatusDate,UserProfileDetail_EnrollId,UserProfileDetail_lastDate,UserInformation_Id,UserInformation_firstName,UserInformation_middleName,UserInformation_lastName,UserInformation_otherNames,UserInformation_UserType_name,UserInformation_primaryState,UserInformation_otherState_0,UserInformation_otherState_1,UserInformation_UserLicense_0_licenseState,UserInformation_UserLicense_0_licenseNumber,UserInformation_UserLicense_0_licenseStatus,UserInformation_Setting,UserInformation_primaryEmail,UserInformation_modifiedAt,UserInformation_createdAt,Eroor_message,Error_extensions_code
User One,10/31/2018 11:42,am**********************************,7/22/2019 12:35,1111122,*****,,*****,,CP,MA,MA,BA,MA,0,,ADMINISTRATIVE,*****@*****.com,,,GraphQL.ExecutionError: 13614711 - NO__DATA,212
User Two,10/31/2019 11:42,am**********************************,7/22/2019 12:35,443333,*****,Jhon,*****,,AP,AK,MP,CLT,KL,220,Valid,ADMINISTRATIVE,*****@*****.com,,,GraphQL.ExecutionError: 13614712 - NO__DATA,212
,,,,,,,,,,,,,,,,,,,,"GraphQL.ExecutionError: Cannot return null for non-null type. Field: PrivilegeFlag, Type: Boolean!.
   at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node)
   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)",ID: 1454790
,,,,,,,,,,,,,,,,,,,,"GraphQL.ExecutionError: Cannot return null for non-null type. Field: admittingArrangementFlag, Type: Boolean!.
   at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node)
   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)",ID: 13614790
```

is there any way to get this format.  i try with following code but not get expected
``` 
StringBuilder msgEr = new StringBuilder();
            using (var w = new ChoCSVWriter(msgEr)
                .WithFirstLineHeader()
                )
            {
                using (var r = new ChoJSONReader(@"E:/Temp/CSV/input/Data_Sample.json")
                    .WithJSONPath("$..data.getUsers[*]")
                    .WithJSONPath("$..errors[*]")
                    )
                {
                    w.Write(r);
                }
            }
````
and try with another, different result but not expected
```
 StringBuilder msg1 = new StringBuilder();

            using (var csv = new ChoCSVWriter(msg1).WithFirstLineHeader().WithDelimiter(","))
            {
                using (var json = new ChoJSONReader(@"E:/Temp/CSV/input/Data_Sample.json")
                .WithField("getUsers", jsonPath: "$..data.getUsers[*]")
                .WithField("errors", jsonPath: "$..errors[*]"))

                {
                    csv.Write(json);
                }
            }
```

**Comment by Cinchoo** [comment]
Well this is not straight forward to produce the expected output from json. But I've managed find a way to produce one. Hope this helps.

```
using (var r = new ChoJSONReader(@"C:\Users\nraj39\Downloads\Loan\test1.json")
        .WithJSONPath("$..data.getUsers[*]"))
{
    using (var r1 = new ChoJSONReader(@"C:\Users\nraj39\Downloads\Loan\test1.json")
        .WithJSONPath("$..errors[*]")
        )
    {
        var r3 = r1.ZipOrDefault(r, (i, j) =>
        {
            if (j != null)
            {
                j.Merge(i);
                return j;
            }
            else
                return i;
        });

        using (var w = new ChoCSVWriter(@"C:\Users\nraj39\Downloads\Loan\test1.csv")
            .WithFirstLineHeader()
            .Configure(c => c.MaxScanRows = 10)
            .Configure(c => c.ThrowAndStopOnMissingField = false)
            )
        {
            w.Write(r3);
        }
    }
}
```

Take the prerelease package and give it a try.

**Comment by Kunjahamed-P** [comment]
It's Working, thanks. need help too,i add to get count of json element using count(). it show some error when write function . the error is "Cannot read from a closed TextReader."
the code is..
```
using (var r = new ChoJSONReader(@"C:\Users\nraj39\Downloads\Loan\test1.json")
        .WithJSONPath("$..data.getUsers[*]"))
{
int pcount=r.count();
    using (var r1 = new ChoJSONReader(@"C:\Users\nraj39\Downloads\Loan\test1.json")
        .WithJSONPath("$..errors[*]")
        )
    {
        var r3 = r1.ZipOrDefault(r, (i, j) =>
        {
            if (j != null)
            {
                j.Merge(i);
                return j;
            }
            else
                return i;
        });

        using (var w = new ChoCSVWriter(@"C:\Users\nraj39\Downloads\Loan\test1.csv")
            .WithFirstLineHeader()
            .Configure(c => c.MaxScanRows = 10)
            .Configure(c => c.ThrowAndStopOnMissingField = false)
            )
        {
            w.Write(r3);
        }
    }
}
```

**Comment by Cinchoo** [comment]
all readers are forward only. In order to get the count of nodes as well as to use them for serialization, you must convert them to array.

```
using (var r = new ChoJSONReader(@"C:\Users\nraj39\Downloads\Loan\test1.json")
        .WithJSONPath("$..data.getUsers[*]"))
{
    var arr = r.ToArray();
    int pcount = arr.Length;

    using (var r1 = new ChoJSONReader(@"C:\Users\nraj39\Downloads\Loan\test1.json")
        .WithJSONPath("$..errors[*]")
        )
    {
        var r3 = r1.ZipOrDefault(arr, (i, j) =>
        {
            if (j != null)
            {
                j.Merge(i);
                return j;
            }
            else
                return i;
        });

        using (var w = new ChoCSVWriter(@"C:\Users\nraj39\Downloads\Loan\test1.csv")
            .WithFirstLineHeader()
            .Configure(c => c.MaxScanRows = 10)
            .Configure(c => c.ThrowAndStopOnMissingField = false)
            )
        {
            w.Write(r3);
        }
    }
}
```

**Comment by Kunjahamed-P** [comment]
its working, thanks
