### ISSUE TITLE
Quotes in header throws exception

### ISSUE THREAD

**Issue by mihaimyh** [Cinchoo/ChoETL#77]
Presuming in the header I have quotes around the fields, is there any way I can use ChoCSVReader to parse it?

`"5108","mesg_s_umid","mesg_validation_requested","mesg_validation_passed","mesg_class","mesg_related_s_umid","mesg_is_text_readonly","mesg_is_delete_inhibited","mesg_is_text_modified","mesg_is_partial","mesg_status","mesg_crea_appl_serv_name","mesg_crea_mpfn_name","mesg_crea_rp_name","mesg_crea_oper_nickname","mesg_crea_date_time","mesg_mod_oper_nickname","mesg_mod_date_time","mesg_verf_oper_nickname","mesg_recordversion",":E:mesg_account_name",":E:mesg_account_number",":E:mesg_appl_sender_referencereference",":E:mesg_approver_nickname",":E:mesg_auth_delv_notif_req",":E:mesg_authoriser_dn",":E:mesg_b2b_instructions",":E:mesg_batch_reference",":E:mesg_beneficiary_account",":E:mesg_beneficiary_address",":E:mesg_beneficiary_bank_code",":E:mesg_beneficiary_bank_name",":E:mesg_beneficiary_name",":E:mesg_cas_sender_reference",":E:mesg_cas_target_rp_name",":E:mesg_charges",":E:mesg_contract_id",":E:mesg_copy_recipient_dn",":E:mesg_copy_service_cid",":E:mesg_copy_service_id",":E:mesg_copy_state",":E:mesg_copy_type",":E:mesg_credeb_account_number",":E:mesg_credit_amount",":E:mesg_credit_ccy",":E:mesg_custom_keyword1",":E:mesg_custom_keyword2",":E:mesg_custom_keyword3",":E:mesg_data_keyword1",":E:mesg_data_keyword2",":E:mesg_data_keyword3",":E:mesg_debit_account_instructing",":E:mesg_debit_amount",":E:mesg_debit_ccy",":E:mesg_delv_notif_req_mtype",":E:mesg_delv_notif_req_recDN",":E:mesg_delv_overdue_warn_req",":E:mesg_digest_value",":E:mesg_dirty",":E:mesg_e2e_transaction_reference",":E:mesg_exchange_rate",":E:mesg_expiry_date_time",":E:mesg_file_desc",":E:mesg_file_digest_algo",":E:mesg_file_digest_value",":E:mesg_file_header_info",":E:mesg_file_info",":E:mesg_file_logical_name",":E:mesg_file_size",":E:mesg_fin_ccy_amount",":E:mesg_fin_inform_release_info",":E:mesg_fin_value_date",":E:mesg_force_completed",":E:mesg_frmt_name",":E:mesg_has_verifiable_field",":E:mesg_identifier",":E:mesg_instructions",":E:mesg_intermediary_bank_code",":E:mesg_is_copy",":E:mesg_is_copy_required",":E:mesg_is_live",":E:mesg_is_recipient_list_public",":E:mesg_is_retrieved",":E:mesg_is_simplified_screen",":E:mesg_locked_template",":E:mesg_mesg_user_group",":E:mesg_nature",":E:mesg_network_appl_ind",":E:mesg_network_delv_notif_req",":E:mesg_network_obso_period",":E:mesg_network_priority",":E:mesg_nrs_required_sig_nbr",":E:mesg_odering_party_address",":E:mesg_odering_party_institution",":E:mesg_odering_party_name",":E:mesg_orig_snf_ref",":E:mesg_originator_account_id",":E:mesg_originator_address",":E:mesg_originator_name",":E:mesg_overdue_warning_delay",":E:mesg_overdue_warning_time",":E:mesg_payload_attribute_name",":E:mesg_payload_attribute_value",":E:mesg_payload_type",":E:mesg_pc_info_for_receiver",":E:mesg_possible_dup_creation",":E:mesg_product_name",":E:mesg_product_version",":E:mesg_rcv_charges_amount",":E:mesg_rcv_charges_curr",":E:mesg_receiver_alia_name",":E:mesg_receiver_swift_address",":E:mesg_recipient_list",":E:mesg_recovery_accept_info",":E:mesg_regulatory_reporting",":E:mesg_rel_trn_ref",":E:mesg_release_info",":E:mesg_remit_info",":E:mesg_request_e2e_control",":E:mesg_request_type",":E:mesg_requestor_dn",":E:mesg_retrieval_info",":E:mesg_rma_checked",":E:mesg_security_iapp_name",":E:mesg_security_required",":E:mesg_sender_X1",":E:mesg_sender_X2",":E:mesg_sender_X3",":E:mesg_sender_X4",":E:mesg_sender_branch_info",":E:mesg_sender_city_name",":E:mesg_sender_corr_type",":E:mesg_sender_ctry_code",":E:mesg_sender_ctry_name",":E:mesg_sender_institution_name",":E:mesg_sender_location",":E:mesg_sender_swift_address",":E:mesg_service",":E:mesg_signature_digest_reference",":E:mesg_signature_digest_value",":E:mesg_sla",":E:mesg_snd_charges_amount",":E:mesg_snd_charges_curr",":E:mesg_snep_profile_name",":E:mesg_source_template_name",":E:mesg_sub_format",":E:mesg_syntax_table_ver",":E:mesg_templ_prep_status",":E:mesg_template_descr",":E:mesg_template_name",":E:mesg_third_party_list",":E:mesg_tran_num",":E:mesg_transaction_date",":E:mesg_transfer_desc",":E:mesg_transfer_info",":E:mesg_trn_ref",":E:mesg_type",":E:mesg_use_pki_signature",":E:mesg_user_issued_as_pde",":E:mesg_user_priority_code",":E:mesg_user_reference_text",":E:mesg_uumid",":E:mesg_uumid_suffix",":E:mesg_vendor_name",":E:mesg_xml_query_ref1",":E:mesg_xml_query_ref2",":E:mesg_xml_query_ref3",":E:mesg_xmlv2_digest_value",":E:mesg_xmty_upload_id",":E:mesg_xmty_uri",":E:mesg_xsvc_uri",":E:mesg_z_approval_trailer",":E:mesg_zz41_is_possible_dup",
`

```
foreach (dynamic rec in new ChoCSVReader(@"D:\user\Downloads\temp\20200124\mesg_20200124.txt").WithFirstLineHeader()) 
{
    Console.WriteLine($"Id: {rec.mesg_s_umid}");
    Console.WriteLine($"Name: {rec.mesg_validation_requested}");
 }
```
```
ChoETL.ChoParserException: Atleast one of the field header is empty. Please check the field headers at [174].
   at ChoETL.ChoCSVRecordReader.GetHeaders(String line)
   at ChoETL.ChoCSVRecordReader.<>c__DisplayClass21_0.<AsEnumerable>b__0(Tuple`2 pair)
   at ChoETL.ChoPeekEnumerator`1.MoveToNext()
   at ChoETL.ChoPeekEnumerator`1.TryFetchPeek()
   at ChoETL.ChoPeekEnumerator`1.get_Peek()
   at ChoETL.ChoCSVRecordReader.AsEnumerable(Object source, TraceSwitch traceSwitch, Func`2 filterFunc)+MoveNext()
   at ChoETL.ChoCSVReader`1.<>c__DisplayClass49_0.<GetEnumerator>b__0()
   at ChoETL.ChoEnumeratorWrapper.ChoEnumeratorWrapperInternal`1.MoveNext()
   at ChoETL.ChoEnumeratorWrapper.BuildEnumerable[T](Func`1 moveNext, Func`1 current, Action dispose)+MoveNext()
```

**Comment by mihaimyh** [comment]
Investigating it further it seems that not the quotes are the issue here but the last comma in the header. Is there a way to ignore the last comma if there is no value after it?

**Comment by mihaimyh** [comment]
Got it by passing `IgnoreColumnsWithEmptyHeader = true` in ConfigureHeader().
